name: ${GITHUB_REPOSITORY}

on:
  push:
    branches:
      - main

jobs:
  front:
    name: front
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push my shit to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./front
          dockerfile: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FRONT_IMAGE_NAME }}:latest
  back:
    name: back
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push my shit to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./back
          dockerfile: ./back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.BACK_IMAGE_NAME }}:latest

