version: '3.8'

services:
  neuro_front:
    image: githubname/image_name:latest
    env_file:
      - .env_neuro
    restart: unless-stopped
    depends_on:
      - neuro_back
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  neuro_back:
    image: githubname/image_name:latest
    env_file:
      - .env_neuro
    restart: unless-stopped
    ports:
      - "8528:8000"
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./back/data:/app/data

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app_network:
    driver: bridge

volumes:
  qdrant_data:
    driver: local