import os

from dotenv import load_dotenv

load_dotenv()

MONGO_URI = os.getenv('MONGO_URI')
EMBEDDING_MODEL_NAME = os.getenv('EMBEDDING_MODEL_NAME',)
RERANKER_MODEL_NAME = os.getenv('RERANKER_MODEL_NAME')
QDRANT_HOST = os.getenv('QDRANT_HOST', 'localhost')
QDRANT_PORT = int(os.getenv('QDRANT_PORT', 6333))
OPENAI_API_BASE = os.getenv('OPENAI_API_BASE',)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', 'DUMMY_KEY')
OPENAI_MODEL_NAME = os.getenv('OPENAI_MODEL_NAME', )
QDRANT_COLLECTION_NAME = os.getenv('QDRANT_COLLECTION_NAME')
UPLOAD_FOLDER = 'uploads_telegram'
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'docx'}
VALID_CATEGORIES = ["Lookup", "Calculation"]

TOTAL_CONTEXT_WINDOW_TOKENS = int(os.getenv('TOTAL_CONTEXT_WINDOW_TOKENS', 16000))
RESPONSE_BUFFER_TOKENS = int(os.getenv('RESPONSE_BUFFER_TOKENS', 4096))
BASE_PROMPT_TOKENS = 800
MAX_HISTORY_MESSAGES_TO_FETCH = 15
MAX_QDRANT_RESULTS_TO_FETCH = 20
QDRANT_SCORE_THRESHOLD = 0.6
MIN_RERANK_SCORE = 0.8
VECTOR_SIZE = 1024
